// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW370dG9UILX_Vh43W6vtYPq8TupnaXRU',
    appId: '1:263065310534:web:a296c2118b3cbbdbdc4147',
    messagingSenderId: '263065310534',
    projectId: 'hooptracker-799e8',
    authDomain: 'hooptracker-799e8.firebaseapp.com',
    databaseURL: 'https://hooptracker-799e8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hooptracker-799e8.appspot.com',
    measurementId: 'G-HTNK6W6WHK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIbCZPoRbST8d8poViZLdLfSyDTiA4Xzc',
    appId: '1:263065310534:android:195aac37eaba2d34dc4147',
    messagingSenderId: '263065310534',
    projectId: 'hooptracker-799e8',
    databaseURL: 'https://hooptracker-799e8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hooptracker-799e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAObG6PyD03MImjVmNNPROI9pkD9DbZdPA',
    appId: '1:263065310534:ios:a9946f2660784ae5dc4147',
    messagingSenderId: '263065310534',
    projectId: 'hooptracker-799e8',
    databaseURL: 'https://hooptracker-799e8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hooptracker-799e8.appspot.com',
    iosClientId: '263065310534-6ioo58mc8lrgsgnc9a1vuvv54c96239k.apps.googleusercontent.com',
    iosBundleId: 'com.example.hooptracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAObG6PyD03MImjVmNNPROI9pkD9DbZdPA',
    appId: '1:263065310534:ios:a9946f2660784ae5dc4147',
    messagingSenderId: '263065310534',
    projectId: 'hooptracker-799e8',
    databaseURL: 'https://hooptracker-799e8-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'hooptracker-799e8.appspot.com',
    iosClientId: '263065310534-6ioo58mc8lrgsgnc9a1vuvv54c96239k.apps.googleusercontent.com',
    iosBundleId: 'com.example.hooptracker',
  );
}
